import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class ReportGenerator:
    """Generates geological reports in markdown format."""
    
    def generate_classification_report(self, prediction: Dict[str, Any], user_info: Dict[str, Any]) -> str:
        rock_type = prediction.get("rock_type", "Unknown")
        lithology_class = prediction.get("lithology_class", "Unknown")
        confidence = prediction.get("confidence_score", 0.0)
        minerals = prediction.get("mineral_predictions", {})
        
        mineral_list = "\n".join([f"- **{min_name}**: {float(prob)*100:.1f}% confidence" for min_name, prob in minerals.items()])
        
        report = f"""# Geological Lithology Classification Report

## 1. Executive Summary
This document presents the automated petrographic and lithological classification results for the drill core sample, processed using the Automated Lithology Classification System.

## 2. Sample & Metadata Information
- **Sample ID**: {prediction.get("id", "N/A")}
- **Original Filename**: {prediction.get("original_filename", "Unknown")}
- **Processed By**: {user_info.get("username", "System Operator")}
- **Date Generated**: {prediction.get("created_at", "Just now")}

## 3. Classification Results
- **Rock Type Category**: {rock_type}
- **Lithology Classification**: **{lithology_class}**
- **Classification Confidence**: {confidence:.2f}%
- **Model Executed**: {prediction.get("model_used", "EfficientNet-B3")}

## 4. Mineralogical Predictions
The following minerals were identified and quantified in the drill core sample:
{mineral_list if minerals else "- No specific minerals detected."}

## 5. Geological Interpretation
Based on the visual classification as **{lithology_class}** (classified as a {rock_type} rock) and the associated mineralogical makeup:
- The presence of this lithology indicates a specific formation history characteristic of {rock_type.lower()} geological settings.
- Further geological verification and thin-section analysis are recommended to confirm these visual predictions.

## 6. Recommendations
1. Conduct core logging correlation to verify lateral continuity.
2. Cross-reference results with wireline logging logs (Gamma Ray, Density).
3. Save this report in the borehole database.

---
*Report automatically generated by Automated Lithology Classification System.*
"""
        return report

    def generate_borehole_report(self, predictions: List[Dict[str, Any]], borehole_info: Dict[str, Any]) -> str:
        report = f"""# Borehole Summarized Geological Report

## Borehole Information
- **Borehole Name**: {borehole_info.get("name", "BH-001")}
- **Total Samples**: {len(predictions)}
- **Location/Coordinates**: {borehole_info.get("location", "N/A")}
- **Drill Date**: {borehole_info.get("date", "N/A")}

## Lithological Sequence
Below is the sequence of core samples classified by depth:

"""
        for i, pred in enumerate(predictions):
            report += f"### Sample {i+1} (Depth: {pred.get('depth', i*5)}m)\n"
            report += f"- **Lithology**: {pred.get('lithology_class', 'Unknown')}\n"
            report += f"- **Confidence**: {pred.get('confidence_score', 0.0):.2f}%\n"
            report += f"- **Minerals**: {', '.join(pred.get('mineral_predictions', {}).keys())}\n\n"
            
        return report

    def format_prediction_summary(self, prediction: Dict[str, Any]) -> str:
        return f"Rock: {prediction.get('lithology_class')} ({prediction.get('rock_type')}), Confidence: {prediction.get('confidence_score', 0.0):.2f}%"
