import io
import os
import logging
from typing import Dict, Any, Optional
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

logger = logging.getLogger(__name__)

class ReportService:
    """Generates professional PDF reports from predictions using ReportLab."""
    
    def generate_pdf_report(self, prediction: Dict[str, Any], user: Dict[str, Any], report_content: str) -> bytes:
        logger.info(f"Generating PDF report for prediction {prediction.get('id')}")
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )
        
        styles = getSampleStyleSheet()
        
        # Define colors matching the enterprise theme
        primary_color = colors.HexColor("#6366f1") # Indigo
        secondary_color = colors.HexColor("#06b6d4") # Cyan
        text_color = colors.HexColor("#0f172a") # Dark slate
        
        # Custom styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=primary_color,
            spaceAfter=15
        )
        
        subtitle_style = ParagraphStyle(
            'ReportSubTitle',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=secondary_color,
            spaceAfter=10
        )
        
        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontSize=10,
            textColor=text_color,
            leading=14,
            spaceAfter=6
        )
        
        bold_body_style = ParagraphStyle(
            'ReportBodyBold',
            parent=body_style,
            fontName='Helvetica-Bold'
        )

        elements = []
        
        # Title
        elements.append(Paragraph("GEOLOGICAL REPORT", title_style))
        elements.append(Paragraph("Automated Lithology Classification & Mineralogical Assessment", subtitle_style))
        elements.append(Spacer(1, 15))
        
        # Metadata Table
        metadata_data = [
            [Paragraph("Sample ID", bold_body_style), Paragraph(str(prediction.get("id", "N/A")), body_style),
             Paragraph("Rock Type", bold_body_style), Paragraph(str(prediction.get("rock_type", "Unknown")), body_style)],
            [Paragraph("Lithology Class", bold_body_style), Paragraph(str(prediction.get("lithology_class", "Unknown")), body_style),
             Paragraph("Confidence Score", bold_body_style), Paragraph(f"{prediction.get('confidence_score', 0.0):.2f}%", body_style)],
            [Paragraph("Model Used", bold_body_style), Paragraph(str(prediction.get("model_used", "EfficientNet-B3")), body_style),
             Paragraph("Generated By", bold_body_style), Paragraph(str(user.get("username", "System Operator")), body_style)]
        ]
        
        meta_table = Table(metadata_data, colWidths=[120, 130, 120, 130])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        
        elements.append(meta_table)
        elements.append(Spacer(1, 20))
        
        # Add Image if available
        image_path = prediction.get("image_path")
        if image_path and os.path.exists(image_path):
            try:
                # Add image scaled proportionally
                img = Image(image_path, width=200, height=150)
                img.hAlign = 'CENTER'
                elements.append(Paragraph("<b>Sample Core Image Analyzed:</b>", body_style))
                elements.append(Spacer(1, 5))
                elements.append(img)
                elements.append(Spacer(1, 20))
            except Exception as e:
                logger.error(f"Could not render image in PDF: {e}")
        
        # Minerals Table
        elements.append(Paragraph("Identified Minerals & Predicted Abundance", subtitle_style))
        minerals = prediction.get("mineral_predictions", {})
        if minerals:
            mineral_data = [[Paragraph("Mineral Name", bold_body_style), Paragraph("Estimated Percentage", bold_body_style)]]
            for min_name, val in minerals.items():
                pct = float(val) * 100
                mineral_data.append([Paragraph(min_name, body_style), Paragraph(f"{pct:.2f}%", body_style)])
            
            min_table = Table(mineral_data, colWidths=[250, 250])
            min_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#e2e8f0")),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                ('PADDING', (0,0), (-1,-1), 6),
            ]))
            elements.append(min_table)
        else:
            elements.append(Paragraph("No mineral quantification performed or stored.", body_style))
            
        elements.append(Spacer(1, 20))
        
        # RAG / Detailed Report Text
        elements.append(Paragraph("Detailed AI Geological Analysis", subtitle_style))
        # Split report content into paragraphs to avoid overlapping or breaking ReportLab
        paragraphs = report_content.split("\n\n")
        for p in paragraphs:
            if p.strip():
                clean_p = p.replace("#", "").replace("**", "<b>").replace("</b><b>", "").replace("*", "")
                elements.append(Paragraph(clean_p, body_style))
                
        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()

report_service = ReportService()
